### PR TITLE
rearrange PCG_HAS_128BIT_OPS guards to compile without __SIZEOF_INT128__

### LINKED ISSUE #11: Compile failure on 32-bit Mac OS X
Current master fails to compile on Mac OS X 10.10 when compiling for i386 (32-bit). 

```
$ CFLAGS=-m32 LDFLAGS=-m32 make
cd src; /Applications/Xcode.app/Contents/Developer/usr/bin/make
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-advance-8.o pcg-advance-8.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-advance-16.o pcg-advance-16.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-advance-32.o pcg-advance-32.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-advance-64.o pcg-advance-64.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-advance-128.o pcg-advance-128.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-output-8.o pcg-output-8.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-output-16.o pcg-output-16.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-output-32.o pcg-output-32.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-output-64.o pcg-output-64.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-output-128.o pcg-output-128.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-rngs-8.o pcg-rngs-8.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-rngs-16.o pcg-rngs-16.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-rngs-32.o pcg-rngs-32.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-rngs-64.o pcg-rngs-64.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-rngs-128.o pcg-rngs-128.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-global-32.o pcg-global-32.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-global-64.o pcg-global-64.c
pcg-global-32.c:35:38: error: use of undeclared identifier 'PCG_STATE_SETSEQ_64_INITIALIZER'
static pcg32_random_t pcg32_global = PCG32_INITIALIZER;
                                     ^
../include/pcg_variants.h:2178:33: note: expanded from macro 'PCG32_INITIALIZER'
#define PCG32_INITIALIZER       PCG_STATE_SETSEQ_64_INITIALIZER
                                ^
1 error generated.
make[1]: *** [pcg-global-32.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

Digging a little more, seems to be related to the absence of 128-bit ops (PCG_HAS_128BIT_OPS is undefined). Any ideas? 

Thanks!

### PR DESCRIPTION
**Pull request by ehmry**
Fix #11

### CODE REVIEW

**Comment by imneme** [comment]
It looks like you're moving some 64-bit things behind the guard?

**Comment by ehmry** [comment]
@imneme yes, my bad, fixed at 8b718adecdc5ecb64aeeab7ab7e03d37b6269ce0

**Comment by imneme** [comment]
Thanks!
