### ISSUE TITLE
Compile failure on 32-bit Mac OS X

### ISSUE THREAD

**Issue by spencersalazar** [imneme/pcg-c#11]
Current master fails to compile on Mac OS X 10.10 when compiling for i386 (32-bit). 

```
$ CFLAGS=-m32 LDFLAGS=-m32 make
cd src; /Applications/Xcode.app/Contents/Developer/usr/bin/make
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-advance-8.o pcg-advance-8.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-advance-16.o pcg-advance-16.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-advance-32.o pcg-advance-32.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-advance-64.o pcg-advance-64.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-advance-128.o pcg-advance-128.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-output-8.o pcg-output-8.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-output-16.o pcg-output-16.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-output-32.o pcg-output-32.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-output-64.o pcg-output-64.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-output-128.o pcg-output-128.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-rngs-8.o pcg-rngs-8.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-rngs-16.o pcg-rngs-16.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-rngs-32.o pcg-rngs-32.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-rngs-64.o pcg-rngs-64.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-rngs-128.o pcg-rngs-128.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-global-32.o pcg-global-32.c
cc -m32 -O3 -std=c99 -I../include  -c -o pcg-global-64.o pcg-global-64.c
pcg-global-32.c:35:38: error: use of undeclared identifier 'PCG_STATE_SETSEQ_64_INITIALIZER'
static pcg32_random_t pcg32_global = PCG32_INITIALIZER;
                                     ^
../include/pcg_variants.h:2178:33: note: expanded from macro 'PCG32_INITIALIZER'
#define PCG32_INITIALIZER       PCG_STATE_SETSEQ_64_INITIALIZER
                                ^
1 error generated.
make[1]: *** [pcg-global-32.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

Digging a little more, seems to be related to the absence of 128-bit ops (PCG_HAS_128BIT_OPS is undefined). Any ideas? 

Thanks!

**Comment by domenkozar** [comment]
Same on NixOS: http://hydra.nixos.org/build/25146085/nixlog/1/raw

**Comment by ulfhanebutte** [comment]
I run into the same issue on a Cray XC30 system

The issue seems related to the test of #if __SIZEOF_INT128__ on line 48 in pcg_variants.h
as a hack, try taking the test out.  and  set     typedef __uint128_t pcg128_t;

A second issue in extras/pcg_spinlock.h, the  #ifndef __has_include test is failing 
as a hack take test out and set  #define INCLUDE_OKAY(x) 1

The code compiled and was able to build libraries and run the tests
Performing a quick sanity check...
All tests succeeded.
make[1]: Leaving directory `pcg-c/test-low'
cd test-high; make test
make[1]: Entering directory `pcg-c/test-high'
sh run-tests.sh
Performing a quick sanity check...
All tests succeeded.
make[1]: Leaving directory pcg-c/test-high'
